angular.module('myApp',['ui.router']).config(function($stateProvider,$urlRouterProvider){
	$stateProvider.state('home',{
		url:'/home',
		views:{
			'':{
				templateUrl:'templates/home.html',
				controller:'homeCtrl',
				controllerAs:'home'
			}
		}
	})
	.state('aboutus',{
		url:'/aboutus',
		views:{
			'':{
				templateUrl:'templates/aboutus.html',
				controller:'aboutusCtrl',
				controllerAs:'aboutus'
			}
		}
	})
	.state('services',{
		url:'/services',
		views:{
			'':{
				templateUrl:'templates/services.html',
				controller:'servicesCtrl',
				controllerAs:'services'
			}
		}
	})
	.state('contactus',{
		url:'/contactus',
		views:{
			'':{
				templateUrl:'templates/contactus.html',
				controller:'contactusCtrl',
				controllerAs:'contactus'
			}
		}
	});
	$urlRouterProvider.otherwise('/home');
});